title: Haveno
email: havenodex@protonmail.com
description: Monero-based decentralized P2P exchange
baseurl: ""
url: "https://haveno-dex.github.io/haveno-site"
twitter_username: HavenoDEX
keywords: "monero, xmr, bitcoin, btc, cryptocurrency, exchange, p2p, tor"

# Build settings
plugins:
  - jekyll-feed

exclude: ["README.md", LICENSE]

sitemap:
  exclude:
    - "/404.html"