title: Haveno
email: havenodex@protonmail.com
description: Decentralized P2P exchange based on Monero and Tor
baseurl: ""
url: "https://haveno.exchange"
twitter_username: HavenoDEX
keywords: "monero, xmr, bitcoin, btc, cryptocurrency, exchange, p2p, tor"

permalink: pretty

# paginate
paginate: 6
paginate_path: "/blog/page:num/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

sitemap:
  exclude:
    - "/404.html"